---
- name: to install apache in my ubuntu machine
  become: yes
  hosts: ubuntu
  tasks: 
    - name: i am going to update apt module
      apt: 
        upgrade: yes
        update_cache: yes
    - name: i m going t install apache2
      apt:
        name=apache2 state=present
    - name: i m going to start my apache2 
      service:
        name: apache2
        state: started